[env]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-esp32-c6
framework = arduino
src_filter =
    +<common/*>
    +<${PIOENV}/*>
lib_deps =
    mathertel/OneButton@^2.6.2
    fastled/FastLED@^3.10.3
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:scoreboard]

[env:remote_control]